version: "3.9"

services:
  web:
    build: ./src
    restart: on-failure
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - db

  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db

networks:
  db:
    driver: bridge
